# Name of workflow
name: Lint, Build and Test

# Trigger workflow on all pull requests
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      # Run lint
      - name: Lint client
        run: npm run lint
        working-directory: ./client

      - name: Lint server
        run: npm run lint
        working-directory: ./server

      # Run build
      # - name: Build client
      #   run: npm run build
      #   working-directory: ./client

      # - name: Build server
      #   run: npm run build
      #   working-directory: ./server

      # Run tests
      # - name: Test client
      #   run: npm run test
      #   working-directory: ./client

      # - name: Test server
      #   run: npm run test
      #   working-directory: ./server
